/**
 * `region` is derived from `hqCountry`, never stored independently: `CompanySchema` rejects a
 * record whose `region` is not `regionOf(hqCountry)`. Ported from v1's
 * `backend/src/providers/regions.ts` and extended to the full ISO-3166-1 alpha-2 list so a company
 * from anywhere gets a real region instead of "Other".
 */

export const REGIONS = [
  "North America",
  "South America",
  "Europe",
  "Middle East",
  "Africa",
  "Asia",
  "Oceania",
  "Other",
] as const;
export type Region = (typeof REGIONS)[number];

export const REGION_BY_COUNTRY: Readonly<Record<string, Region>> = {
  // North America (incl. Central America and the Caribbean)
  US: "North America",
  CA: "North America",
  MX: "North America",
  GT: "North America",
  BZ: "North America",
  SV: "North America",
  HN: "North America",
  NI: "North America",
  CR: "North America",
  PA: "North America",
  CU: "North America",
  DO: "North America",
  HT: "North America",
  JM: "North America",
  TT: "North America",
  BS: "North America",
  BB: "North America",
  AG: "North America",
  DM: "North America",
  GD: "North America",
  KN: "North America",
  LC: "North America",
  VC: "North America",
  PR: "North America",
  BM: "North America",
  GL: "North America",
  KY: "North America",
  VG: "North America",
  AW: "North America",
  CW: "North America",
  SX: "North America",
  TC: "North America",
  AI: "North America",
  MS: "North America",
  BQ: "North America",
  BL: "North America",
  MF: "North America",
  GP: "North America",
  MQ: "North America",
  PM: "North America",
  VI: "North America",

  // South America
  BR: "South America",
  AR: "South America",
  CL: "South America",
  CO: "South America",
  PE: "South America",
  VE: "South America",
  EC: "South America",
  BO: "South America",
  PY: "South America",
  UY: "South America",
  GY: "South America",
  SR: "South America",
  GF: "South America",
  FK: "South America",

  // Europe
  GB: "Europe",
  IE: "Europe",
  FR: "Europe",
  ES: "Europe",
  PT: "Europe",
  DE: "Europe",
  NL: "Europe",
  BE: "Europe",
  LU: "Europe",
  IT: "Europe",
  CH: "Europe",
  AT: "Europe",
  SE: "Europe",
  NO: "Europe",
  DK: "Europe",
  FI: "Europe",
  IS: "Europe",
  EE: "Europe",
  LV: "Europe",
  LT: "Europe",
  PL: "Europe",
  CZ: "Europe",
  SK: "Europe",
  HU: "Europe",
  SI: "Europe",
  HR: "Europe",
  BA: "Europe",
  RS: "Europe",
  ME: "Europe",
  MK: "Europe",
  AL: "Europe",
  XK: "Europe",
  BG: "Europe",
  RO: "Europe",
  GR: "Europe",
  MT: "Europe",
  CY: "Europe",
  MD: "Europe",
  UA: "Europe",
  BY: "Europe",
  RU: "Europe",
  MC: "Europe",
  LI: "Europe",
  AD: "Europe",
  SM: "Europe",
  VA: "Europe",
  GI: "Europe",
  FO: "Europe",
  AX: "Europe",
  GG: "Europe",
  JE: "Europe",
  IM: "Europe",
  SJ: "Europe",

  // Middle East
  IL: "Middle East",
  AE: "Middle East",
  SA: "Middle East",
  QA: "Middle East",
  KW: "Middle East",
  BH: "Middle East",
  OM: "Middle East",
  JO: "Middle East",
  LB: "Middle East",
  SY: "Middle East",
  IQ: "Middle East",
  IR: "Middle East",
  YE: "Middle East",
  PS: "Middle East",
  TR: "Middle East",

  // Africa
  EG: "Africa",
  NG: "Africa",
  KE: "Africa",
  ZA: "Africa",
  MA: "Africa",
  DZ: "Africa",
  TN: "Africa",
  LY: "Africa",
  SD: "Africa",
  SS: "Africa",
  ET: "Africa",
  ER: "Africa",
  DJ: "Africa",
  SO: "Africa",
  UG: "Africa",
  TZ: "Africa",
  RW: "Africa",
  BI: "Africa",
  GH: "Africa",
  CI: "Africa",
  SN: "Africa",
  ML: "Africa",
  BF: "Africa",
  NE: "Africa",
  TD: "Africa",
  CM: "Africa",
  CF: "Africa",
  GA: "Africa",
  CG: "Africa",
  CD: "Africa",
  AO: "Africa",
  ZM: "Africa",
  ZW: "Africa",
  MW: "Africa",
  MZ: "Africa",
  BW: "Africa",
  NA: "Africa",
  LS: "Africa",
  SZ: "Africa",
  MG: "Africa",
  MU: "Africa",
  SC: "Africa",
  KM: "Africa",
  CV: "Africa",
  GM: "Africa",
  GN: "Africa",
  GW: "Africa",
  LR: "Africa",
  SL: "Africa",
  TG: "Africa",
  BJ: "Africa",
  MR: "Africa",
  EH: "Africa",
  ST: "Africa",
  GQ: "Africa",
  RE: "Africa",
  YT: "Africa",
  SH: "Africa",

  // Asia
  IN: "Asia",
  CN: "Asia",
  JP: "Asia",
  KR: "Asia",
  KP: "Asia",
  TW: "Asia",
  HK: "Asia",
  MO: "Asia",
  SG: "Asia",
  MY: "Asia",
  ID: "Asia",
  TH: "Asia",
  VN: "Asia",
  PH: "Asia",
  MM: "Asia",
  KH: "Asia",
  LA: "Asia",
  BN: "Asia",
  TL: "Asia",
  MN: "Asia",
  BD: "Asia",
  PK: "Asia",
  LK: "Asia",
  NP: "Asia",
  BT: "Asia",
  MV: "Asia",
  AF: "Asia",
  KZ: "Asia",
  UZ: "Asia",
  TM: "Asia",
  KG: "Asia",
  TJ: "Asia",
  GE: "Asia",
  AM: "Asia",
  AZ: "Asia",

  // Oceania
  AU: "Oceania",
  NZ: "Oceania",
  FJ: "Oceania",
  PG: "Oceania",
  SB: "Oceania",
  VU: "Oceania",
  NC: "Oceania",
  PF: "Oceania",
  WS: "Oceania",
  TO: "Oceania",
  KI: "Oceania",
  TV: "Oceania",
  NR: "Oceania",
  FM: "Oceania",
  MH: "Oceania",
  PW: "Oceania",
  CK: "Oceania",
  NU: "Oceania",
  GU: "Oceania",
  MP: "Oceania",
  AS: "Oceania",
  WF: "Oceania",
  TK: "Oceania",
  NF: "Oceania",
};

export function regionOf(country: string): Region {
  return REGION_BY_COUNTRY[country.toUpperCase()] ?? "Other";
}
